//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный текст был создан автоматически: Microsoft.VSDesigner, версия: 4.0.30319.34014.
// 
#pragma warning disable 1591

namespace Service.RNG {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DataExchangeSoapBinding", Namespace="http://www.dataexchange.org")]
    public partial class DataExchange : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ВыполнитьАлгоритмИПолучитьРезультатOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DataExchange() {
            this.Url = global::Service.Properties.Settings.Default.Service_RNG_DataExchange;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ВыполнитьАлгоритмИПолучитьРезультатCompletedEventHandler ВыполнитьАлгоритмИПолучитьРезультатCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("ВыполнитьАлгоритмИПолучитьРезультат", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ВыполнитьАлгоритмИПолучитьРезультатResponse", Namespace="http://www.dataexchange.org")]
        public ВыполнитьАлгоритмИПолучитьРезультатResponse ВыполнитьАлгоритмИПолучитьРезультат([System.Xml.Serialization.XmlElementAttribute("ВыполнитьАлгоритмИПолучитьРезультат", Namespace="http://www.dataexchange.org")] ВыполнитьАлгоритмИПолучитьРезультат ВыполнитьАлгоритмИПолучитьРезультат1) {
            object[] results = this.Invoke("ВыполнитьАлгоритмИПолучитьРезультат", new object[] {
                        ВыполнитьАлгоритмИПолучитьРезультат1});
            return ((ВыполнитьАлгоритмИПолучитьРезультатResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ВыполнитьАлгоритмИПолучитьРезультатAsync(ВыполнитьАлгоритмИПолучитьРезультат ВыполнитьАлгоритмИПолучитьРезультат1) {
            this.ВыполнитьАлгоритмИПолучитьРезультатAsync(ВыполнитьАлгоритмИПолучитьРезультат1, null);
        }
        
        /// <remarks/>
        public void ВыполнитьАлгоритмИПолучитьРезультатAsync(ВыполнитьАлгоритмИПолучитьРезультат ВыполнитьАлгоритмИПолучитьРезультат1, object userState) {
            if ((this.ВыполнитьАлгоритмИПолучитьРезультатOperationCompleted == null)) {
                this.ВыполнитьАлгоритмИПолучитьРезультатOperationCompleted = new System.Threading.SendOrPostCallback(this.OnВыполнитьАлгоритмИПолучитьРезультатOperationCompleted);
            }
            this.InvokeAsync("ВыполнитьАлгоритмИПолучитьРезультат", new object[] {
                        ВыполнитьАлгоритмИПолучитьРезультат1}, this.ВыполнитьАлгоритмИПолучитьРезультатOperationCompleted, userState);
        }
        
        private void OnВыполнитьАлгоритмИПолучитьРезультатOperationCompleted(object arg) {
            if ((this.ВыполнитьАлгоритмИПолучитьРезультатCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ВыполнитьАлгоритмИПолучитьРезультатCompleted(this, new ВыполнитьАлгоритмИПолучитьРезультатCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dataexchange.org")]
    public partial class ВыполнитьАлгоритмИПолучитьРезультат {
        
        private string идентификаторField;
        
        private string параметрыАлгоритмаField;
        
        private System.Nullable<bool> сжиматьРезультатField;
        
        private bool сжиматьРезультатFieldSpecified;
        
        private System.Nullable<bool> режимОтладкиField;
        
        private bool режимОтладкиFieldSpecified;
        
        private System.Nullable<bool> jSONField;
        
        private bool jSONFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Идентификатор {
            get {
                return this.идентификаторField;
            }
            set {
                this.идентификаторField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ПараметрыАлгоритма {
            get {
                return this.параметрыАлгоритмаField;
            }
            set {
                this.параметрыАлгоритмаField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> СжиматьРезультат {
            get {
                return this.сжиматьРезультатField;
            }
            set {
                this.сжиматьРезультатField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool СжиматьРезультатSpecified {
            get {
                return this.сжиматьРезультатFieldSpecified;
            }
            set {
                this.сжиматьРезультатFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> РежимОтладки {
            get {
                return this.режимОтладкиField;
            }
            set {
                this.режимОтладкиField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool РежимОтладкиSpecified {
            get {
                return this.режимОтладкиFieldSpecified;
            }
            set {
                this.режимОтладкиFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> JSON {
            get {
                return this.jSONField;
            }
            set {
                this.jSONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool JSONSpecified {
            get {
                return this.jSONFieldSpecified;
            }
            set {
                this.jSONFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dataexchange.org")]
    public partial class ВыполнитьАлгоритмИПолучитьРезультатResponse {
        
        private string выполнитьАлгоритмИПолучитьРезультатResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ВыполнитьАлгоритмИПолучитьРезультатResult {
            get {
                return this.выполнитьАлгоритмИПолучитьРезультатResultField;
            }
            set {
                this.выполнитьАлгоритмИПолучитьРезультатResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void ВыполнитьАлгоритмИПолучитьРезультатCompletedEventHandler(object sender, ВыполнитьАлгоритмИПолучитьРезультатCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ВыполнитьАлгоритмИПолучитьРезультатCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ВыполнитьАлгоритмИПолучитьРезультатCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ВыполнитьАлгоритмИПолучитьРезультатResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ВыполнитьАлгоритмИПолучитьРезультатResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591