//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный текст был создан автоматически: Microsoft.VSDesigner, версия: 4.0.30319.34014.
// 
#pragma warning disable 1591

namespace Service.RNG {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DataExchangeSoapBinding", Namespace="http://www.dataexchange.org")]
    public partial class DataExchange : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ВыполнитьАлгоритмИПолучитьРезультатOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DataExchange() {
            this.Url = global::Service.Properties.Settings.Default.Service_RNG_DataExchange;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ВыполнитьАлгоритмИПолучитьРезультатCompletedEventHandler ВыполнитьАлгоритмИПолучитьРезультатCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.dataexchange.org#DataExchange:ВыполнитьАлгоритмИПолучитьРезультат", RequestNamespace="http://www.dataexchange.org", ResponseNamespace="http://www.dataexchange.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string ВыполнитьАлгоритмИПолучитьРезультат(string Идентификатор, string ПараметрыАлгоритма, bool СжиматьРезультат, bool РежимОтладки, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<bool> JSON) {
            object[] results = this.Invoke("ВыполнитьАлгоритмИПолучитьРезультат", new object[] {
                        Идентификатор,
                        ПараметрыАлгоритма,
                        СжиматьРезультат,
                        РежимОтладки,
                        JSON});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ВыполнитьАлгоритмИПолучитьРезультатAsync(string Идентификатор, string ПараметрыАлгоритма, bool СжиматьРезультат, bool РежимОтладки, System.Nullable<bool> JSON) {
            this.ВыполнитьАлгоритмИПолучитьРезультатAsync(Идентификатор, ПараметрыАлгоритма, СжиматьРезультат, РежимОтладки, JSON, null);
        }
        
        /// <remarks/>
        public void ВыполнитьАлгоритмИПолучитьРезультатAsync(string Идентификатор, string ПараметрыАлгоритма, bool СжиматьРезультат, bool РежимОтладки, System.Nullable<bool> JSON, object userState) {
            if ((this.ВыполнитьАлгоритмИПолучитьРезультатOperationCompleted == null)) {
                this.ВыполнитьАлгоритмИПолучитьРезультатOperationCompleted = new System.Threading.SendOrPostCallback(this.OnВыполнитьАлгоритмИПолучитьРезультатOperationCompleted);
            }
            this.InvokeAsync("ВыполнитьАлгоритмИПолучитьРезультат", new object[] {
                        Идентификатор,
                        ПараметрыАлгоритма,
                        СжиматьРезультат,
                        РежимОтладки,
                        JSON}, this.ВыполнитьАлгоритмИПолучитьРезультатOperationCompleted, userState);
        }
        
        private void OnВыполнитьАлгоритмИПолучитьРезультатOperationCompleted(object arg) {
            if ((this.ВыполнитьАлгоритмИПолучитьРезультатCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ВыполнитьАлгоритмИПолучитьРезультатCompleted(this, new ВыполнитьАлгоритмИПолучитьРезультатCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void ВыполнитьАлгоритмИПолучитьРезультатCompletedEventHandler(object sender, ВыполнитьАлгоритмИПолучитьРезультатCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ВыполнитьАлгоритмИПолучитьРезультатCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ВыполнитьАлгоритмИПолучитьРезультатCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591